DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL,
    PRIMARY KEY(id)
);



insert into accounts(name, balance) 
values ('Bob', 10000);

begin;
insert into accounts(name, balance) 
values ('Alice', 10000);
commit work;
select * from accounts;


begin;

update accounts 
set balance = balance - 1000
where id = 1;

update accounts 
set balance = balance + 1000
where id = 3;

commit;


select * from accounts;

insert into accounts(id, name, balance) values 
(2, 'Jack', 0);

select * from accounts order by id;

begin;

update accounts 
set balance = balance - 1000
where id = 1;

update accounts 
set balance = balance + 1000
where id = 2;

rollback;